<a href="https://colab.research.google.com/github/jyj1206/BDA_9th_ML1/blob/main/3%EC%A3%BC%EC%B0%A8_%EA%B5%90%EC%B0%A8%EA%B2%80%EC%A6%9D2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 교차검증

## cross_val_score

In [1]:
# 라이브러리 불러오기
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_breast_cancer
import numpy as np

In [2]:
# 유방암 데이터 불러오기
cancer = load_breast_cancer()
X, y = cancer.data, cancer.target

In [3]:
# 모델 불러오기
clf = DecisionTreeClassifier(random_state=42)

In [4]:
clf

DecisionTreeClassifier(random_state=42)

In [5]:
# cross_val_score 실행
from sklearn.model_selection import cross_val_score, StratifiedKFold
stkfold= StratifiedKFold(n_splits=5) # StratifedKFold 객체 생성
scores = cross_val_score(clf, X, y, cv=stkfold, scoring='accuracy')

In [6]:
# 결과 확인
scores.mean()

0.9173420276354604

## cross_validate

In [7]:
# cross_validate 실행
from sklearn.model_selection import cross_validate
result = cross_validate(clf, X, y, cv=stkfold, scoring='accuracy', return_train_score=True)

In [8]:
result

{'fit_time': array([0.0179739 , 0.04110456, 0.02816725, 0.02140546, 0.01551175]),
 'score_time': array([0.00191808, 0.00186276, 0.00174117, 0.00175762, 0.00304961]),
 'test_score': array([0.9122807 , 0.90350877, 0.92982456, 0.95614035, 0.88495575]),
 'train_score': array([1., 1., 1., 1., 1.])}

In [9]:
scorings = ['accuracy','precision','recall']
cross_validate(clf, X,y, cv =stkfold, scoring=  scorings, return_train_score=True)

{'fit_time': array([0.01112533, 0.03517032, 0.02170658, 0.02876234, 0.02578163]),
 'score_time': array([0.01459217, 0.02121377, 0.02793479, 0.01290464, 0.02858472]),
 'test_accuracy': array([0.9122807 , 0.90350877, 0.92982456, 0.95614035, 0.88495575]),
 'train_accuracy': array([1., 1., 1., 1., 1.]),
 'test_precision': array([0.95522388, 0.91666667, 0.93243243, 0.95890411, 0.96774194]),
 'train_precision': array([1., 1., 1., 1., 1.]),
 'test_recall': array([0.90140845, 0.92957746, 0.95833333, 0.97222222, 0.84507042]),
 'train_recall': array([1., 1., 1., 1., 1.])}

In [10]:
# 펭귄 데이터 교차검증 실행
import seaborn as sns
df = sns.load_dataset('penguins')

# 결측치 처리(0으로 채움)
df.fillna(0, inplace=True)

In [11]:
# 클래스 종류 확인
df.species.value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [12]:
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             0.0            0.0                0.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             0.0            0.0                0.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            0.0       0  
4         3450.0  Female  
..           ...     ...  
339          0.0       0  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]

In [13]:
# X, y 데이터 준비
df_x = df.drop(['island','species', 'sex'], axis=1)
df_y = df.species

In [14]:
clf = RandomForestClassifier(random_state=42)

In [15]:
# 교차검증 (오류)
scorings = ['accuracy', 'precision', 'recall', 'f1']
cross_validate(clf, df_x, df_y, cv=stkfold, scoring=scorings, return_train_score=True)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:1000: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 139, in __call__
    score = scorer._score(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 376, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 2204, in precision_score
    p, _, _, _ = precision_recall_fscore_support(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/l

{'fit_time': array([0.30460191, 0.32315421, 0.43603992, 0.57297683, 0.42095566]),
 'score_time': array([0.0211792 , 0.01901698, 0.01672482, 0.01737642, 0.01749992]),
 'test_accuracy': array([0.95652174, 0.98550725, 0.97101449, 0.98550725, 0.95588235]),
 'train_accuracy': array([1.        , 0.99636364, 0.99636364, 0.99636364, 1.        ]),
 'test_precision': array([nan, nan, nan, nan, nan]),
 'train_precision': array([nan, nan, nan, nan, nan]),
 'test_recall': array([nan, nan, nan, nan, nan]),
 'train_recall': array([nan, nan, nan, nan, nan]),
 'test_f1': array([nan, nan, nan, nan, nan]),
 'train_f1': array([nan, nan, nan, nan, nan])}

> ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].
> - 위와같은 경고 발생, 이 경우 오류에 해결방법 처럼 기본적인 'precision', 'recall', 'f1'은 average 파라미터를 'binary'로 사용 때문에 [None, 'micro', 'macro', 'weighted'] 이중 하나를 선택해주어야함

In [16]:
# 교차검증 (micro)
scorings = ['accuracy', 'precision_micro', 'recall_micro', 'f1_micro']
cross_validate(clf, df_x, df_y, cv=stkfold, scoring=scorings, return_train_score=True)

{'fit_time': array([0.44552612, 0.34699368, 0.34934568, 0.39621353, 0.47634768]),
 'score_time': array([0.02282858, 0.03041887, 0.02675986, 0.03471017, 0.02196741]),
 'test_accuracy': array([0.95652174, 0.98550725, 0.97101449, 0.98550725, 0.95588235]),
 'train_accuracy': array([1.        , 0.99636364, 0.99636364, 0.99636364, 1.        ]),
 'test_precision_micro': array([0.95652174, 0.98550725, 0.97101449, 0.98550725, 0.95588235]),
 'train_precision_micro': array([1.        , 0.99636364, 0.99636364, 0.99636364, 1.        ]),
 'test_recall_micro': array([0.95652174, 0.98550725, 0.97101449, 0.98550725, 0.95588235]),
 'train_recall_micro': array([1.        , 0.99636364, 0.99636364, 0.99636364, 1.        ]),
 'test_f1_micro': array([0.95652174, 0.98550725, 0.97101449, 0.98550725, 0.95588235]),
 'train_f1_micro': array([1.        , 0.99636364, 0.99636364, 0.99636364, 1.        ])}

In [17]:
## 다양한 모델을 사용
#DecisionTreeClassifier, RandomForestClassifier, SVC

models = [DecisionTreeClassifier(random_state=42), RandomForestClassifier(random_state=42), SVC(random_state=42)]
name =['DT','RF','LR']

for model, name in zip(models, name):
    print('###사용 알고리즘',name,'###')
    for score in ['accuracy','precision_micro','recall_micro','f1_micro']:
        print(score)
        print("-" * 20)
        print(cross_val_score(model, df_x,df_y, cv=stkfold, scoring=score))

###사용 알고리즘 DT ###
accuracy
--------------------
[0.95652174 1.         0.91304348 0.95652174 0.94117647]
precision_micro
--------------------
[0.95652174 1.         0.91304348 0.95652174 0.94117647]
recall_micro
--------------------
[0.95652174 1.         0.91304348 0.95652174 0.94117647]
f1_micro
--------------------
[0.95652174 1.         0.91304348 0.95652174 0.94117647]
###사용 알고리즘 RF ###
accuracy
--------------------
[0.95652174 0.98550725 0.97101449 0.98550725 0.95588235]
precision_micro
--------------------
[0.95652174 0.98550725 0.97101449 0.98550725 0.95588235]
recall_micro
--------------------
[0.95652174 0.98550725 0.97101449 0.98550725 0.95588235]
f1_micro
--------------------
[0.95652174 0.98550725 0.97101449 0.98550725 0.95588235]
###사용 알고리즘 LR ###
accuracy
--------------------
[0.72463768 0.68115942 0.71014493 0.73913043 0.75      ]
precision_micro
--------------------
[0.72463768 0.68115942 0.71014493 0.73913043 0.75      ]
recall_micro
--------------------
[0.72463768 0

# 임계점

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [19]:
# train, test 분리
X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.3,random_state=42)

In [20]:
# 모델 생성
clf = RandomForestClassifier(random_state=42)

In [21]:
def get_clf_eval(y_test, pred):
    conf = confusion_matrix(y_test, pred)
    acc = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred, average='micro')
    recall = recall_score(y_test, pred, average ='micro')

    print(conf)
    print(acc, precision, recall)

In [22]:
# 모델 학습
clf.fit(X_train, y_train)

# 예측
pred = clf.predict(X_test)

# 성능 평가
get_clf_eval(y_test, pred)

[[47  2  1]
 [ 0 20  0]
 [ 0  0 34]]
0.9711538461538461 0.9711538461538461 0.9711538461538461


In [23]:
# 각 클래스에 속할 확률을 예측
clf.predict_proba(X_test)

array([[0.01, 0.99, 0.  ],
       [0.16, 0.84, 0.  ],
       [0.  , 0.  , 1.  ],
       [0.07, 0.93, 0.  ],
       [0.07, 0.39, 0.54],
       [0.  , 0.  , 1.  ],
       [0.  , 0.01, 0.99],
       [0.16, 0.07, 0.77],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 0.  , 1.  ],
       [0.98, 0.02, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.91, 0.09, 0.  ],
       [0.  , 0.01, 0.99],
       [1.  , 0.  , 0.  ],
       [0.89, 0.11, 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 0.  , 1.  ],
       [0.94, 0.06, 0.  ],
       [0.98, 0.02, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [0.04, 0.96, 0.  ],
       [0.07, 0.93, 0.  ],
       [0.83, 0.14, 0.03],
       [0.05, 0.95, 0.  ],
       [0.99, 0.01, 0.  ],
       [0.08, 0.92, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [0.02, 0.98, 0.  ],
       [0.98, 0.02, 0.  ],
       [0.89, 0.03, 0.08],
       [0.94, 0.06, 0.  ],
       [0.  , 0.  , 1.  ],
 